distributable:
  url: https://sourceware.org/pub/valgrind/valgrind-{{version}}.tar.bz2
  strip-components: 1

versions:
  url: https://sourceware.org/pub/valgrind
  match: /valgrind-\d+\.\d+\.\d+\.tar\.bz2/
  strip:
    - /^valgrind-/
    - /\.tar\.bz2$/

platforms:
  - linux

build:
  dependencies:
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    gnu.org/autoconf: '*'
    gnu.org/automake: '*'
    gnu.org/libtool: '*'

  script:
    - ./autogen.sh
    - ./configure $ARGS
    - make --jobs {{ hw.concurrency }} install
  env:
    ARGS:
      - --prefix="{{prefix}}"
      - --disable-dependency-tracking
      - --enable-only64bit
      - --without-mpicc

provides:
  - bin/valgrind

test:
  script:
    - valgrind --version
