distributable:
  url: https://github.com/cyrusimap/cyrus-sasl/releases/download/cyrus-sasl-{{version}}/cyrus-sasl-{{version}}.tar.gz
  strip-components: 1

display-name: cyrus-sasl

versions:
  github: cyrusimap/cyrus-sasl
  strip: /^cyrus-sasl-/

platforms:
  - darwin
  - linux/x86-64

build:
  dependencies:
    kerberos.org: '*'
    openssl.org: ^1.1.1
  script:
    - ./configure $ARGS
    - make --jobs {{ hw.concurrency }} install

  env:
    ARGS:
      - --disable-macos-framework
      - --disable-dependency-tracking
      - --disable-silent-rules
      - --prefix="{{prefix}}"
      - --with-ssl={{ deps.openssl.org.prefix }}

test:
  script:
    cc fixture.cpp "-I{{prefix}}/include", "-L{{prefix}}/lib" -lsasl2
    test "$(./a.out)" = "20 SGVsbG8sIHdvcmxkIQ=="
