distributable:
  url: https://github.com/argoproj/argo-cd/archive/refs/tags/v{{ version }}.tar.gz
  strip-components: 1

versions:
  github: argoproj/argo-cd/releases/tags
  strip: /^v/

build:
  dependencies:
    cmake.org: ^3
    tea.xyz/gx/cc: c99
    tea.xyz/gx/make: '*'
    git-scm.org: '*'
    go.dev: '^1.14'
    nodejs.org: '*'
    classic.yarnpkg.com: '*'
  script: |
    make dep-ui-local
    NODE_ENV=production NODE_ONLINE_ENV=online yarn --cwd ui build
    make cli-local
    make install

test:
  script: |
    # test help message
    assert_match "argocd controls a Argo CD server", $(argocd --help)
    # test config file
    touch argocd-config
    chmod 0600 ./argocd-config
    # expected output
    assert_match "CURRENT  NAME  SERVER\n", $(argocd context --config ./argocd-config)